controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    arm_position_controller:
      type: position_controllers/JointGroupPositionController

wheel_velocity_controller:
  ros__parameters:
    joints:
      - Frontleft_joint
      - FrontRight_joint
      - BackLeft_joint
      - BackRight_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

arm_position_controller:
  ros__parameters:
    joints:
      - Arm_joint1
      - Arm_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
